import React from 'react';

const sqlScript = `-- 1. Create the 'messages' table to store chat history
CREATE TABLE public.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    text text,
    sender text CHECK (sender IN ('user', 'bot')),
    images jsonb
);

-- 2. Add comments for clarity
COMMENT ON TABLE public.messages IS 'Stores chat messages for each user.';
COMMENT ON COLUMN public.messages.user_id IS 'Links to the user who owns the message.';
COMMENT ON COLUMN public.messages.sender IS 'Identifies if the message came from the user or the bot.';
COMMENT ON COLUMN public.messages.images IS 'Stores an array of image data attached to a message.';


-- 3. Enable Row Level Security (RLS) to protect user data
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 4. Create security policies
-- This policy allows users to see ONLY their own messages.
CREATE POLICY "Allow users to view their own messages"
ON public.messages
FOR SELECT
USING (auth.uid() = user_id);

-- This policy allows users to create messages ONLY for themselves.
CREATE POLICY "Allow users to insert their own messages"
ON public.messages
FOR INSERT
WITH CHECK (auth.uid() = user_id);
`;

const DatabaseSetupError: React.FC = () => {
    const [copied, setCopied] = React.useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(sqlScript).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    return (
        <div className="h-full flex flex-col items-center justify-center bg-gray-50 p-4 text-gray-800">
            <div className="w-full max-w-sm mx-auto bg-white p-6 rounded-xl shadow-md border border-gray-100 text-center">
                <i className="fa-solid fa-database text-4xl text-red-500 mb-4"></i>
                <h1 className="text-xl font-bold text-slate-800 mb-2">Database Setup Required</h1>
                <p className="text-sm text-gray-600 mb-4">
                    The application needs a 'messages' table in your Supabase database to store chat history, but it seems to be missing.
                </p>
                <p className="text-sm text-gray-600 mb-4">
                    Please run the following SQL script in your Supabase project's <strong>SQL Editor</strong> to create the table and set up security policies.
                </p>

                <div className="relative bg-gray-100 rounded-md p-2 my-4 text-left">
                    <pre className="text-xs overflow-x-auto whitespace-pre-wrap break-all">
                        <code className="font-mono">{sqlScript}</code>
                    </pre>
                    <button 
                        onClick={handleCopy}
                        className="absolute top-2 right-2 px-2 py-1 text-xs bg-gray-200 text-gray-700 rounded hover:bg-gray-300 transition-colors"
                    >
                        {copied ? 'Copied!' : 'Copy'}
                    </button>
                </div>

                <p className="text-xs text-gray-500">
                    After running the script, please refresh this page.
                </p>
            </div>
        </div>
    );
};

export default DatabaseSetupError;
